# Generated by Django 3.2.3 on 2025-04-13 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='scheduled', max_length=20)),
                ('appointment_date', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actual_date', models.DateTimeField(blank=True, null=True)),
                ('dentist', models.ForeignKey(limit_choices_to={'role': 3}, on_delete=django.db.models.deletion.PROTECT, related_name='dentist_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.PROTECT, related_name='patient_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-appointment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['dentist', 'appointment_date'], name='records_rec_dentist_4675f1_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['patient', 'appointment_date'], name='records_rec_patient_7feab9_idx'),
        ),
    ]
