# Generated by Django 3.2.3 on 2025-04-13 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='dentist',
            field=models.ForeignKey(limit_choices_to={'role_id': 3}, on_delete=django.db.models.deletion.PROTECT, related_name='dentist_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role_id': 2}, on_delete=django.db.models.deletion.PROTECT, related_name='patient_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
