# Generated by Django 3.1.12 on 2025-02-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role_id',
            field=models.PositiveIntegerField(default=2, verbose_name='Role'),
        ),
    ]