version: '3.8'

services:

  frontend:
    container_name: front
    build:
      context: ./dentistry/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./dentistry
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=your_db_name
    restart: unless-stopped

  db:
    container_name: mongo
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
