version: '3.8'

services:
  frontend:
    build:
      context: ./dentistry/frontend
    container_name: front
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./dentistry
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_NAME=dentistry_db
      - MONGO_DB_USER=admin
      - MONGO_DB_PASSWORD=your_secure_password
      - MONGO_AUTH_SOURCE=admin
    command: >
      sh -c "/wait-for-it.sh mongo:27017 --timeout=30 --strict -- 
              python manage.py migrate && 
              python manage.py runserver 0.0.0.0:8000"

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mongo_data:
