version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - VITE_API_MOCK=${VITE_API_MOCK}
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - app-network