version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    networks:
      - app-network
  
  backend:
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=yourdomain.com,backend
    networks:
      - app-network