version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "127.0.0.1:5173:5173"
    environment:
      - VITE_API_MOCK=${VITE_API_MOCK}
    # depends_on:
    #   - backend
    volumes:
      - ../frontend:/app
      - /app/node_modules
