version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,backend
      - SECRET_KEY=your-secret-key-here
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=core.settings
    volumes:
      - backend_media:/app/media
      - backend_static:/app/static
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongodb_data:
  backend_media:
  backend_static:


networks:
  app-network:
    driver: bridge
