# Generated by Django 3.1.12 on 2025-03-17 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('experience_years', models.PositiveIntegerField()),
                ('cabinet_number', models.CharField(max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('user', models.OneToOneField(limit_choices_to={'role_id': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
